@REM This file was automatically generated by alyxlib.
@REM Run this file before uploading your addon to the workshop, then follow window instructions after uploading.
@echo off


IF NOT EXIST "../../../../../../../../Projects/alyx" (
echo AlyxLib folder wasn't found, cannot perform this batch file! Please rerun alyxlib.py to setup correctly...
PAUSE
EXIT
)

del "scripts/vscripts/alyxlib"
del "scripts/vscripts/game"

echo Symlinks have been removed, continue after uploading to workshop.
PAUSE
echo.

mklink "/home/sunny/.steam/steam/steamapps/common/Half-Life Alyx/content/hlvr_addons/feddi_maya_collab/scripts/vscripts/alyxlib" "/home/sunny/Projects/alyx/scripts/vscripts/alyxlib"
echo.
mklink "/home/sunny/.steam/steam/steamapps/common/Half-Life Alyx/content/hlvr_addons/feddi_maya_collab/scripts/vscripts/game" "/home/sunny/Projects/alyx/scripts/vscripts/game"
echo.

echo Symlinks reinstated! This window can now be closed.
PAUSE
